AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a Launch Template and an ASG

Parameters:
  BaseName:
    Description: Base name for the created resources
    Type: String

  DesiredCapacity:
    Description: Number of instances for the ASG
    Type: Number
    Default: 1

Resources:
  # Launch Template Definition
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${BaseName}-LaunchTemplate"
      LaunchTemplateData:
        InstanceType: t3.micro
        ImageId: ami-0c55b159cbfafe1f0 # Replace with a valid Amazon Linux 2 AMI ID for your region
        KeyName: my-key-pair # Replace with your key pair name if required
        SecurityGroupIds:
          - sg-12345678 # Replace with a valid security group ID

  # Auto Scaling Group Definition
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${BaseName}-ASG"
      MinSize: '1'
      MaxSize: '5'
      DesiredCapacity: !Ref DesiredCapacity
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - subnet-12345678  # Replace with a valid subnet ID
